[workspace]
members = [
    "ligeia-core",
    "ligeia-vcd",
    "ligeia-svcb",
    "ligeia",
]

[profile.release]
debug = true
incremental = true
split-debuginfo = 'packed'
strip = 'none'

[profile.dev]
opt-level = 1
