[package]
name = "ligeia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
pollster = "0.2.5"
winit = "0.26.1"
bytemuck = "1.10.0"
