[package]
name = "load-vcd"
version = "0.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ligeia-vcd = { path = "../../ligeia-vcd" }
number_prefix = "0.4.0"
